version: '3.8'

services:
  deployflow:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: deployflow_app
    restart: always
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=sqlite:///./deployflow.db # Update if using a different DB