version: '3.8'

services:
  deployflow-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: deployflow_master
    restart: always
    ports:
      - "80:8000"